services:
    qcharts.directory.directory_service:
        class: QCharts\CoreBundle\Service\Directory\DirectoryService
        arguments:
            - "@qcharts.directory.repository"
            - "@qcharts.serializer"