services:
    qcharts.user_formatter:
        class: QCharts\CoreBundle\Service\UserFormatter
    qcharts.user_service:
        class: QCharts\CoreBundle\Service\UserService
        arguments:
            - "@qcharts.user_repo"
            - "@qcharts.serializer_factory"
            - "@fos_user.user_manager"
            - "@qcharts.user_formatter"
    qcharts.user_registration_success.subscriber:
        class: QCharts\CoreBundle\EventSubscriber\UserRegistrationSubscriber
        arguments: []
        tags:
            - { name: kernel.event_subscriber }
    qcharts.user_registration.form:
        class: QCharts\CoreBundle\Form\UserRegistrationType
        tags:
            - { name: form.type, alias: core_user_registration_form }