qcharts.api.favorite_get:
    path: /api/favorite
    defaults: { _controller: ApiBundle:Favorite:getFavorites }
    methods: [ GET ]
qcharts.api.favorite_add:
    path: /api/favorite
    defaults: { _controller: ApiBundle:Favorite:registerFavorite }
    methods: [ POST ]
qcharts.api.favorite_remove:
    path: /api/favorite
    defaults: { _controller: ApiBundle:Favorite:removeFavorite }
    methods: [ DELETE ]